# Generated by Django 2.1.2 on 2018-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0003_herobanner_logoimage1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigImage', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('groupBachelor', models.CharField(max_length=255)),
                ('titleClarification', models.CharField(max_length=255)),
                ('logoTxt', models.CharField(max_length=2)),
                ('shortTextTop', models.TextField()),
                ('shortTextMini', models.CharField(max_length=255)),
                ('yearsLong', models.IntegerField()),
                ('tuitonFee', models.FloatField()),
                ('tuitonFeeHasClarification', models.BooleanField()),
                ('tuitonFeeClarification', models.TextField()),
                ('creditsTotal', models.IntegerField()),
                ('leafletHas', models.BooleanField()),
                ('leafletUrl', models.URLField()),
                ('hasOutline', models.BooleanField()),
                ('outlineXMLDATA', models.TextField()),
            ],
        ),
    ]
