# Generated by Django 2.1.2 on 2018-11-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0004_programdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroGlobalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoImage1', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
