# Generated by Django 2.1.2 on 2018-11-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0005_heroglobaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='description2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='tuitonFeeClarification',
            field=models.TextField(default=''),
        ),
    ]
