# Generated by Django 2.1.2 on 2018-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0007_globaltextandtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerTitle', models.CharField(max_length=255)),
                ('bannerLine1', models.CharField(max_length=255)),
                ('bannerLine2', models.CharField(max_length=255)),
            ],
        ),
    ]
