# Generated by Django 2.1.2 on 2018-11-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0008_bloggeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramsGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextBig1', models.CharField(max_length=255)),
            ],
        ),
    ]
