# Generated by Django 2.1.2 on 2018-11-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0009_programsgeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonsGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TalkToAdmission', models.CharField(max_length=255)),
                ('GetLeaf', models.CharField(max_length=255)),
                ('Scholarship', models.CharField(max_length=255)),
            ],
        ),
    ]
