# Generated by Django 2.1.2 on 2018-11-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0010_buttonsgeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonsgeneral',
            name='GetLeafShort',
            field=models.CharField(default='Get', max_length=50),
        ),
        migrations.AddField(
            model_name='buttonsgeneral',
            name='ScholarshipShort',
            field=models.CharField(default='Get', max_length=50),
        ),
        migrations.AddField(
            model_name='buttonsgeneral',
            name='TalkToAdmissionShort',
            field=models.CharField(default='Talk', max_length=50),
        ),
    ]
