# Generated by Django 2.1.2 on 2018-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0011_auto_20181123_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdata',
            name='tuitonFee',
            field=models.CharField(default='15,500*', max_length=50),
        ),
    ]
