# Generated by Django 2.1.2 on 2018-11-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0012_auto_20181124_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsgeneral',
            name='PlanOutlineTitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
