# Generated by Django 2.1.2 on 2018-11-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0013_programsgeneral_planoutlinetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsgeneral',
            name='FutureBanner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='programsgeneral',
            name='FutureBanner_SecondLine',
            field=models.CharField(default='', max_length=255),
        ),
    ]
