# Generated by Django 2.1.2 on 2018-11-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0014_auto_20181124_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsgeneral',
            name='FutureBanner_FirstLine',
            field=models.CharField(default='', max_length=255),
        ),
    ]
