# Generated by Django 2.1.2 on 2018-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0015_programsgeneral_futurebanner_firstline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsgeneral',
            name='FutureBanner_FirstLine',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
