# Generated by Django 2.1.2 on 2018-11-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0016_auto_20181124_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsgeneral',
            name='FutureBanner_FirstLine',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
