# Generated by Django 2.1.2 on 2018-11-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0017_auto_20181124_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='futureBlock',
            field=models.TextField(default=''),
        ),
    ]
