# Generated by Django 2.1.2 on 2018-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0019_programdata_futureblock_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsgeneral',
            name='DegreeBanner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='programsgeneral',
            name='DegreeBanner_FirstLine',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='programsgeneral',
            name='DegreeBanner_SecondLine',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
