# Generated by Django 2.1.2 on 2018-11-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0020_auto_20181124_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='degreeBlock',
            field=models.TextField(default=''),
        ),
    ]
