# Generated by Django 2.1.2 on 2018-11-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0021_programdata_degreeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
