# Generated by Django 2.1.2 on 2018-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0022_pagegeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegeneral',
            name='bigImage1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='bigImage2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='medImage1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='medImage2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='minImage1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='minImage2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
