# Generated by Django 2.1.2 on 2018-11-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0024_auto_20181124_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nameTitle', models.CharField(max_length=255)),
                ('roleTitle', models.TextField()),
                ('photoBig', models.ImageField(null=True, upload_to='images/people/')),
                ('photoMed', models.ImageField(null=True, upload_to='images/people/')),
                ('photoMin', models.ImageField(null=True, upload_to='images/people/')),
                ('photoTxt', models.CharField(max_length=3)),
                ('nationality', models.CharField(max_length=255)),
                ('social', models.TextField()),
                ('about', models.TextField()),
                ('currentPosition', models.TextField()),
                ('programs', models.TextField()),
                ('skills', models.TextField()),
                ('education', models.TextField()),
                ('generalExperience', models.TextField()),
                ('educationalExperience', models.TextField()),
                ('scholarshipLinks', models.TextField()),
                ('otherLinks', models.TextField()),
            ],
        ),
    ]
