# Generated by Django 2.1.2 on 2018-11-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0025_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='currentPosition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='educationalExperience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='generalExperience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='otherLinks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='photoBig',
            field=models.ImageField(blank=True, null=True, upload_to='images/people/'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='photoMed',
            field=models.ImageField(blank=True, null=True, upload_to='images/people/'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='photoMin',
            field=models.ImageField(blank=True, null=True, upload_to='images/people/'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='photoTxt',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='professor',
            name='programs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='roleTitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='scholarshipLinks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='social',
            field=models.TextField(blank=True, default=''),
        ),
    ]
