# Generated by Django 2.1.2 on 2018-11-29 04:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0026_auto_20181129_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='bigRichData',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
