# Generated by Django 2.1.2 on 2018-11-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0027_professor_bigrichdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='educationalExperience',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='generalExperience',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='otherLinks',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='scholarshipLinks',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='skills',
        ),
    ]
