# Generated by Django 2.1.2 on 2018-11-30 03:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0030_buttonsgeneral_basicbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short_name', models.CharField(max_length=255)),
                ('bigImage1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('heroTitle', models.CharField(max_length=100)),
                ('heroDescription', models.CharField(max_length=100)),
                ('leftData', ckeditor.fields.RichTextField(blank=True, default='')),
                ('middleData', ckeditor.fields.RichTextField(blank=True, default='')),
                ('rightData', ckeditor.fields.RichTextField(blank=True, default='')),
            ],
        ),
    ]
