# Generated by Django 2.1.2 on 2018-11-30 04:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0033_auto_20181130_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebasic',
            name='heroDescription',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
