# Generated by Django 2.1.2 on 2018-11-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0034_auto_20181130_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebasic',
            name='useRightData',
            field=models.BooleanField(default=False),
        ),
    ]
