# Generated by Django 2.1.2 on 2018-11-30 05:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0035_pagebasic_userightdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebasic',
            name='middleData',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
