# Generated by Django 2.1.2 on 2018-11-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0037_auto_20181130_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebasic',
            name='invertNavColorTop',
            field=models.BooleanField(default=False),
        ),
    ]
