# Generated by Django 2.1.2 on 2018-11-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0038_pagebasic_invertnavcolortop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdata',
            name='bigImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='creditsTotal',
            field=models.IntegerField(default=124),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='degreeBlock',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='description2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='futureBlock',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='futureBlock_keys',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='groupBachelor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='hasOutline',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='leafletHas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='leafletUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='logoTxt',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='outlineXMLDATA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='shortTextMini',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='shortTextTop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='titleClarification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='tuitonFeeClarification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='tuitonFeeHasClarification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='yearsLong',
            field=models.IntegerField(default=5),
        ),
    ]
