# Generated by Django 2.1.2 on 2018-12-01 21:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0042_auto_20181201_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagegeneral',
            options={'verbose_name_plural': 'Original Contentent Edition'},
        ),
        migrations.AlterField(
            model_name='programdata',
            name='shortTextMini',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
