# Generated by Django 2.1.2 on 2018-12-01 21:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0044_auto_20181201_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdata',
            name='shortTextTop',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
