# Generated by Django 2.1.2 on 2018-12-01 21:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0045_auto_20181201_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdata',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
