# Generated by Django 2.1.2 on 2018-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0048_navsetting_footernav'),
    ]

    operations = [
        migrations.AddField(
            model_name='applybanner',
            name='applyLink',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
