# Generated by Django 2.1.2 on 2018-12-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0049_applybanner_applylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonsgeneral',
            name='TalkToAdmissionLink',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
