# Generated by Django 2.1.2 on 2018-12-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0052_auto_20181202_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='applybanner',
            name='backImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
