# Generated by Django 2.1.2 on 2018-12-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0053_applybanner_backimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWebpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
