# Generated by Django 2.1.2 on 2018-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0056_auto_20181204_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='bigImageA',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='programdata',
            name='bigImageB',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='programdata',
            name='bigImageC',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='programdata',
            name='bigImageD',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
