# Generated by Django 2.1.2 on 2018-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0057_auto_20181208_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='hasImagesHero',
            field=models.BooleanField(default=False),
        ),
    ]
