# Generated by Django 2.1.2 on 2018-12-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0058_programdata_hasimageshero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegeneral',
            name='bigImageA',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='bigImageB',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='bigImageC',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='bigImageD',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pagegeneral',
            name='hasImagesHero',
            field=models.BooleanField(default=False),
        ),
    ]
