# Generated by Django 2.1.2 on 2018-12-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0059_auto_20181209_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='midImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
