# Generated by Django 2.1.2 on 2018-12-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0060_programdata_midimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='navsetting',
            name='floatNav',
            field=models.TextField(blank=True, default=''),
        ),
    ]
