# Generated by Django 2.1.2 on 2018-12-10 19:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0061_navsetting_floatnav'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='futureRich',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
