# Generated by Django 2.1.2 on 2018-12-10 23:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0062_programdata_futurerich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdata',
            name='futureRich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
