# Generated by Django 2.1.2 on 2018-12-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181204_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bigPicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog/'),
        ),
    ]
