# Generated by Django 2.1.2 on 2018-12-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_bigpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Enter the summary here...', max_length=200),
        ),
    ]
