# Generated by Django 2.1.2 on 2018-12-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181205_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
