# Generated by Django 2.1.2 on 2018-12-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0056_auto_20181204_2136'),
        ('blog', '0008_auto_20181205_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='post',
            name='pagesrelated',
            field=models.ManyToManyField(to='aum.PageGeneral'),
        ),
    ]
