# Generated by Django 2.1.2 on 2018-12-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0056_auto_20181204_2136'),
        ('blog', '0013_auto_20181205_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contentRelated',
        ),
        migrations.AddField(
            model_name='post',
            name='pagesrelated',
            field=models.ManyToManyField(to='aum.PageGeneral'),
        ),
    ]
