# Generated by Django 2.1.2 on 2018-12-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181205_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pagesrelated',
            new_name='pagesRelated',
        ),
    ]
