# Generated by Django 2.1.2 on 2018-12-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181205_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pagesRelated',
            field=models.ManyToManyField(blank=True, to='aum.PageGeneral'),
        ),
        migrations.AlterField(
            model_name='post',
            name='professorRelated',
            field=models.ManyToManyField(blank=True, to='aum.Professor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='programRelated',
            field=models.ManyToManyField(blank=True, to='aum.ProgramData'),
        ),
    ]
